### ISSUE TITLE
关于Drive-WM和Panacea的问题

### ISSUE THREAD

**Issue by zhoujiawei3** [f1yfisher/DriveDreamer2#6]
论文中提到Drive-WM是基于3视角视频生成的，您的意思是基于三视角ground truth视频来生成的吗？但是我认为Drive-WM是基于第一帧全视角图像来生成，只是三个reference view缺少一部分condition，而三个stitched view 有生成的refence view video作为 condition。请问是我的理解有问题吗？

**Comment by zhoujiawei3** [comment]
Panacea也是使用生成的第一帧图像来进行作为condition指导视频生成，但是在比较中您使用的第一帧是ground truth图像是吗？

**Comment by zhoujiawei3** [comment]
没事了，没看表注

**Comment by f1yfisher** [comment]
在论文中我们更加关注多视角一致性的来源，对于Drive-WM来说其多视角一致性主要来自于三个不同视角的视频，因此在对比时我们将该方法的condition认为是3视角视频。
对于控制条件是生成还是gt，我们更新了论文并突出这一点。
![image](https://github.com/user-attachments/assets/e0ab8d7d-fc91-4410-a0f1-d9c558606d29)
